eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8087
spring:
  application:
    name: gateway
  #redis配置
  redis:
    host: 
    port: 6379
    password: 
    database: 1
    timeout: 60s
    jedis:
      pool:
        max-active:-1
        max-idle:15
        max-wait:-1s
        min-idle:5